services:
  postgres:
    image: postgres:16
    container_name: psql_khi
    restart: unless-stopped
    build:
      context: .
      dockerfile: Docker_postgresql
    environment:
      POSTGRES_USER: ${DB_ADMIN_USER}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_NAME: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_ADMIN_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - khi_psql_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    networks:
      - app_internal

  app:
    container_name: web_khi
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}

      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: ${DB_USER}
      PG_PASSWORD: ${DB_USER_PASSWORD}
      PG_DATABASE: ${DB_NAME}

      HACKSU_GUILD_ID: ${HACKSU_GUILD_ID}
      KHI_ADM_ROLE: ${KHI_ADM_ROLE}

      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}

      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      TESTING_READ: "C++ is the Best Language, the very best."
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.khi.rule=Host(`ctf.hacksu.com`)"
      - "traefik.http.routers.khi.entrypoints=websecure"
      - "traefik.http.routers.khi.tls.certresolver=letsencrypt"
      - "traefik.http.services.khi.loadbalancer.server.port=80"
    port:
      - "3333:3000" # dev only
    volumes:
      - ./uploads:${UPLOADS_DIR}
      - ./khi_web_logs:/var/log/nginx
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  khi_psql_data:

networks:
  app_internal: