services:
  postgres:
    image: postgres:16
    container_name: psql_khi
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./psql/Dockerfile
    environment:
      POSTGRES_USER: ${PG_ADMIN_USER}
      POSTGRES_PASSWORD: ${PG_ADMIN_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      DB_USER: ${PG_USER}
      DB_USER_PASSWORD: ${PG_PASSWORD}
      DB_NAME: ${PG_DATABASE}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_ADMIN_USER} -d ${PG_DATABASE}"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    volumes:
      - khi_psql_data:/var/lib/postgresql/data
      - ./psql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    networks:
      - app_internal

  handler:
    container_name: handler_khi
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./handler/Dockerfile
    ports:
      - "50000-50050:50000-50050"
    volumes:
      - khi_ctf_exec_files:/app/ctf:ro
    networks:
      - app_internal

  app:
    container_name: web_khi
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # Svelte's CSRF is extremely annoying if ORIGIN is not present
      ORIGIN: ${BETTER_AUTH_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}

      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}

      HACKSU_GUILD_ID: ${HACKSU_GUILD_ID}
      KHI_ADM_ROLE: ${KHI_ADM_ROLE}

      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}

      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      UPLOADS_DIR: /app/uploads
      BIN_UPLOADS_DIR: /app/ctf
      TESTING_READ: "C++ is the Best Language, the very best."
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.khi.rule=Host(`ctf.hacksu.com`)"
      - "traefik.http.routers.khi.entrypoints=websecure"
      - "traefik.http.routers.khi.tls.certresolver=letsencrypt"
      - "traefik.http.services.khi.loadbalancer.server.port=80"
    ports:
      - "3333:3000" # dev only
    volumes:
      - khi_uploads:/app/uploads
      # temp volume (destroyed on recompose on dokploy)
      - ./khi_web_logs:/var/log/nginx

      # Compiled challenge executables will live here.
      # the handler will have read-only access to these
      # files so it can execute them within special jails
      - khi_ctf_exec_files:/app/ctf
    networks:
      - app_internal
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  khi_psql_data:
  khi_uploads:
  khi_ctf_exec_files:

networks:
  app_internal: