listen_addresses = '*'              # allows the service to be reachable by other devices
log_destination = 'stderr'          # or 'stdout'
logging_collector = off             # keeps logs going to stderr directly
log_min_messages = ERROR            # minimum severity to log
log_min_error_statement = ERROR