# log connections
listen_addresses = '*'          
port = 5432
max_connections = 100

# log reports and errors
log_destination = 'stderr'
logging_collector = on          # Enable capturing stderr and csvlog into log files
log_directory = 'log'           # Directory where log files are written
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_statement = 'none'          # none, ddl, mod, all