[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
autostart=true

[program:bun]
directory=/app/build
command=/usr/local/bin/bun /app/build/index.js
autostart=true
autorestart=true
user=www-data
stdout_logfile=/app/bun.out.log
stderr_logfile=/app/bun.err.log