[supervisord]
nodaemon=true

[program:node]
directory=/app
command=/usr/bin/node /app/server.js
autostart=true
autorestart=true
user=www-data
stdout_logfile=/app/node.out.log
stderr_logfile=/app/node.err.log