[supervisord]
nodaemon=true

[program:bun]
directory=/app
command=/usr/local/bin/bun /app/server.js
autostart=true
autorestart=true
user=www-data
stdout_logfile=/app/bun.out.log
stderr_logfile=/app/bun.err.log